import type { AppData } from '../../types';

export const DEFAULT_DATA: AppData = {
  version: '1.0.0',
  accounts: [
    {
      id: 'a1',
      name: 'Cash',
      currency: 'UAH',
      type: 'cash',
      balance: 0,
      color: '#d29922',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'a2',
      name: 'Card',
      currency: 'UAH',
      type: 'card',
      balance: 0,
      color: '#388bfd',
      createdAt: new Date().toISOString(),
    },
  ],
  transactions: [],
  budgets: [],
  transfers: [],
  recurringRules: [],
  chartWidgets: [],
  categories: [
    { id: 'c1', name: 'Salary', type: 'income', color: '#3fb950', isDefault: true },
    { id: 'c2', name: 'Freelance', type: 'income', color: '#388bfd', isDefault: true },
    {
      id: 'c3',
      name: 'Other income',
      type: 'income',
      color: '#a371f7',
      isOther: true,
      isDefault: true,
    },
    { id: 'c4', name: 'Food & Dining', type: 'expense', color: '#d29922', isDefault: true },
    { id: 'c5', name: 'Transport', type: 'expense', color: '#388bfd', isDefault: true },
    { id: 'c6', name: 'Utilities', type: 'expense', color: '#f85149', isDefault: true },
    { id: 'c7', name: 'Entertainment', type: 'expense', color: '#a371f7', isDefault: true },
    { id: 'c8', name: 'Health', type: 'expense', color: '#ec4899', isDefault: true },
    { id: 'c9', name: 'Clothing', type: 'expense', color: '#0e7490', isDefault: true },
    { id: 'c10', name: 'Education', type: 'expense', color: '#3fb950', isDefault: true },
    { id: 'c11', name: 'Subscriptions', type: 'expense', color: '#388bfd', isDefault: true },
    {
      id: 'c12',
      name: 'Other',
      type: 'expense',
      color: '#8b949e',
      isOther: true,
      isDefault: true,
    },
  ],
  settings: {
    rates: { USD: 41.5, EUR: 44.2 },
    defaultCurrency: 'UAH',
    theme: 'dark',
    autoImportRates: false,
    locale: 'en',
  },
};
